### Secret
apiVersion: v1
kind: Secret
metadata: 
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
type: Opaque
data: 
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="       
  RABBITMQ_DEFAULT_PASSWORD: "cm9ib3Nob3AxMjM="  

---

### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.11.25  # Specific stable version
        envFrom:
        - secretRef:
            name: rabbitmq

---

### Service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
    - protocol: TCP 
      port: 5672     # AMQP port
      targetPort: 5672
    - protocol: TCP
      port: 15672    # Management UI port
      targetPort: 15672
